language: node_js
node_js:
  - "7"
sudo: required
dist: trusty
before_install:
  - sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
  - npm install
  - npm run installdev
  - npm run bundle-dev

after_success:

addons:
  artifacts: true

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  on:
    branch: dev-es6
